[package]
name = "brackeysgj"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.13"
macroquad-platformer = "0.1.1"
macroquad-tiled = "0.1"
# egui-macroquad = "0.8.0"